# Numpy 다차원 배열 변수의 Assignment, Shallow Copy, Deep Copy

## Numpy 다차원 배열 변수의 Assignment

In [1]:
import numpy as np

x = np.arange(5)
y = x
print(id(x), id(y))

3104189388720 3104189388720


In [2]:
print("x = ", x)
print("y = ", y)
x[3] = 10
print("x = ", x)
print("y = ", y)

x =  [0 1 2 3 4]
y =  [0 1 2 3 4]
x =  [ 0  1  2 10  4]
y =  [ 0  1  2 10  4]


## Numpy 다차원 배열 변수의 View는 Shallow copy

In [3]:
x = np.arange(5)
print("x = ", x)
y = x[1:4]
print("y = ", y)
print(id(x), id(y))

x =  [0 1 2 3 4]
y =  [1 2 3]
3104211137712 3104190116752


In [4]:
y[1] = 10
print("y = ", y)
print("x = ", x)

y =  [ 1 10  3]
x =  [ 0  1 10  3  4]


####  -> 이런 현상이 나타나는 이유는 x의 일부 원소와 바인딩 되어 만들어진 변수 y는 x의 변수를 공유하기 때문에 위와 같은 현상 발생

In [7]:
x[3] = 20
print("y = ", y)
print("x = ", x)

y =  [ 1 10 20]
x =  [ 0  1 10 20  4]


### 어느 ndarray가 다른 원소를 공유하는 부분을 view라고 함.

In [9]:
xx = x.view()
print(x)
print(xx)

[ 0  1 10 20  4]
[ 0  1 10 20  4]


In [10]:
print(id(x), id(xx))

3104211137712 3104211139632


In [11]:
x[3] = 30
print("x = ", x)
print("xx = ", xx)

x =  [ 0  1 10 30  4]
xx =  [ 0  1 10 30  4]


In [12]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
b = a[:, :, ::2]
print(b.shape)
b

(2, 3, 2)


array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [14]:
b[0,2,0] = 88
b

array([[[ 0,  2],
        [ 4,  6],
        [88, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [15]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [88,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
a[1,2,2] = 220
a

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [ 88,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21, 220,  23]]])

In [17]:
b

array([[[  0,   2],
        [  4,   6],
        [ 88,  10]],

       [[ 12,  14],
        [ 16,  18],
        [ 20, 220]]])

## Numpy 다차원 배열 변수의 Deep Copy : ndarray.copy

In [18]:
import numpy as np
x = np.arange(4)
y = np.copy(x)
z = x.copy()
print("x = ", x)
print("y = ", y)
print("z = ", z)

print(id(x), id(y), id(z))

x =  [0 1 2 3]
y =  [0 1 2 3]
z =  [0 1 2 3]
3104211140208 3104211139824 3104190116752


In [20]:
# 모두 Deep copy이기 때문에 독립된 객체임.
x[1] = 10
print("x = ", x)
print("y = ", y)
print("z = ", z)

x =  [ 0 10  2  3]
y =  [0 1 2 3]
z =  [0 1 2 3]


# Numpy 다차원 배열의 재구성

## Numpy 다차원 배열의 shape 변경

In [21]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
np.arange(6).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
np.arange(6).reshape(-1, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
np.arange(24).reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
np.arange(24).reshape(3,2,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
np.arange(24).reshape(3,-1, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
np.arange(24).reshape(-1,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Numpy 다차원 배열의 shape 변경

In [28]:
a = np.arange(6).reshape(2,3)
a.reshape(6)

array([0, 1, 2, 3, 4, 5])

In [29]:
a = np.arange(6).reshape(2,3)

In [30]:
a.reshape(6,)

array([0, 1, 2, 3, 4, 5])

In [31]:
a = np.arange(6).reshape(2,3)
a.reshape(-1)

array([0, 1, 2, 3, 4, 5])

In [32]:
a = np.arange(6).reshape(2,3)
a.reshape(-1,)

array([0, 1, 2, 3, 4, 5])

In [33]:
a = np.arange(24).reshape(3,2,4)
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
a = np.arange(24).reshape(3,2,4)
a.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [36]:
a = np.arange(24).reshape(3,2,4)
a.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

#### 여기서 a와 b의 주소가 다르기 때문에 a와 b가 다른 객체라 생각할 수 있지만 b는 a의 view이므로 같음.

In [39]:
a = np.arange(24).reshape(3, 2, 4)
b = a.reshape(2,-1)
b[1,3] = 100

print("Address of a:", id(a))
print("Address of b:", id(b))

print(a)
print(b)
print(a[1,1,3])


Address of a: 3104212208880
Address of b: 3104212208208
[[[  0   1   2   3]
  [  4   5   6   7]]

 [[  8   9  10  11]
  [ 12  13  14 100]]

 [[ 16  17  18  19]
  [ 20  21  22  23]]]
[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14 100  16  17  18  19  20  21  22  23]]
100


## ravel() & faltten()

- raval() : 원 배열의 view를 반환
- flatten() : 원 배열의 복사본을 반환

In [41]:
a = np.arange(6).reshape(2,3)
b = a.ravel()
print(b)
c = a.flatten()
print(c)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [42]:
a[0,0] = 10
print("a = ", a)
print("b = ", b)
print("c = ", c)

a =  [[10  1  2]
 [ 3  4  5]]
b =  [10  1  2  3  4  5]
c =  [0 1 2 3 4 5]


## tile()
- 주어진 배열을 이어붙어 새 배열을 만든 후 반환.

In [43]:
np.tile(np.arange(3), 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [44]:
np.tile(np.arange(3), (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [45]:
np.tile(np.arange(6).reshape(2,3), 3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [46]:
np.tile(np.arange(6).reshape(2,3), (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [47]:
a = np.arange(6).reshape(2,3)
b = np.tile(a, (3,2))
a[0,0] = 10
print(b)

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


## stack(), vstack(), hstack()

In [48]:
a = np.arange(3)
b = np.arange(3,6)
c = np.stack((a,b))
print(c)
print(c.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [49]:
d = np.arange(10,16).reshape(2,3)
e = np.stack((c,d), axis = 0)
print(e)
print(e.shape)

# 0 일경우 ->

[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]]
(2, 2, 3)


In [50]:
f = np.stack((c,d), axis = 1)
print(f)
print(f.shape)

# c, d의 0번째 axis를 가지고 이어붙임

[[[ 0  1  2]
  [10 11 12]]

 [[ 3  4  5]
  [13 14 15]]]
(2, 2, 3)


In [52]:
g = np.stack((c,d), axis = 2)
print(g)
print(g.shape) # 2,3 이 앞에오고 뒤에 갯수가 옴.

[[[ 0 10]
  [ 1 11]
  [ 2 12]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]]
(2, 3, 2)


In [53]:
h1 = np.hstack((np.array([1,2]), np.array([3,4])))
print(h1)
print(h1.shape)

[1 2 3 4]
(4,)


In [55]:
h2 = np.hstack((np.array([1,2,3]), np.array([3,4])))
print(h2)
print(h2.shape)
# 원소가 다르면 1차원으로 반환함.

[1 2 3 3 4]
(5,)


In [56]:
h3 = np.hstack((np.array([1,2,3]), np.array([3,4]),  np.array([3,4,5,7])))
print(h3)
print(h3.shape)
# 원소가 다르면 1차원으로 반환함.

[1 2 3 3 4 3 4 5 7]
(9,)


In [57]:
h4 = np.hstack(([1,2], [3,4]))
print(h4)
print(h4.shape)

[1 2 3 4]
(4,)


In [59]:
h5 = np.hstack((c,d))
print(c)
print(d)
print(c.shape)
print(d.shape)
print(h5)
print(h5.shape)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
(2, 3)
(2, 3)
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]
(2, 6)


## hstack을 3차원에서 할 경우 (a,b,c) , (d,e,f)중 a와d , c와 f가 같아야 함.!
-> 결과는 (a,b+e,c) 

In [63]:
aa = np.arange(24).reshape(2,3,4)
bb = np.arange(32).reshape(2,4,4)

h6 = np.hstack((aa,bb))
print(aa.shape)
print(bb.shape)
print(h6.shape)

print(aa)
print(bb)
print(h6)

(2, 3, 4)
(2, 4, 4)
(2, 7, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]
  [16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [64]:
aa = np.arange(3)
bb = np.arange(3,6)
cc = np.arange(6,9)
h7 = np.vstack((aa,bb,cc))
print(h7)
print(h7.shape)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [65]:
aa = np.arange(24).reshape(2,3,4)
bb = np.arange(24, 60).reshape(3,3,4)
h8 = np.vstack((aa,bb))
print(h8)
print(h8.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]]
(5, 3, 4)
