# Numpy 다차원 배열의 속성 변경

In [1]:
import numpy as np
n = np.arange(5)
print(n.dtype)

int32


In [3]:
n[0] = 5

print(n, n.dtype)

[5 1 2 3 4] int32


In [4]:
n[2] = 10.8
print(n, n.dtype)

[ 5  1 10  3  4] int32


In [5]:
m = n.astype(np.int64)
print(m, m.dtype)
print(n, n.dtype)

[ 5  1 10  3  4] int64
[ 5  1 10  3  4] int32


In [6]:
f = n.astype(np.float64)
print(f, f.dtype)

[ 5.  1. 10.  3.  4.] float64


In [7]:
c = n.astype(np.complex128)
print(c, c.dtype)


[ 5.+0.j  1.+0.j 10.+0.j  3.+0.j  4.+0.j] complex128


In [8]:
print(n.dtype)

int32


### n.flags.writeable : 객체의 내용물 변경을 허용하지 않음.

In [12]:
n.flags.writeable = False
# n[0] = 10

# Numpy 다차원 배열 변수와 할당 연산자

In [14]:
import numpy as np

x = np.arange(5)
print(x)
print(id(x))

x+=1
print(x)
print(id(x))

[0 1 2 3 4]
1891371325744
[1 2 3 4 5]
1891371325744


## 새로운 객체를 만들고 그곳에 연산을 저장.

In [15]:
x = np.arange(5)
print(x)
print(id(x))
x = x + 1
print(x)
print(id(x))

[0 1 2 3 4]
1891393771152
[1 2 3 4 5]
1891393772976


In [17]:
import numpy as np
def add1(x):
    x += 1
a = np.arange(5)
print(a)
add1(a)
print(a)

[0 1 2 3 4]
[1 2 3 4 5]


In [18]:
import numpy as np
def add2(x):
    # 객체를 새로 만든 후 연산결과를 저장.
    x = x + 1
a = np.arange(5)
print(a)
add2(a)
print(a)

[0 1 2 3 4]
[0 1 2 3 4]


In [51]:
import numpy as np
def mult1(x):
    # 모든 복합연산자를 사용하면 기존의 객체의 연산 내용을 저장.
    x *= 2
a = np.arange(5)
print(a)
mult1(a)
print(a)

[0 1 2 3 4]
[0 2 4 6 8]


In [46]:
import numpy as np
def mult2(x):
    x = x * 2
a = np.arange(5)
print(a)
mult2(a)
print(a)

[0 1 2 3 4]
[0 1 2 3 4]


In [47]:
a = 3
print(id(a))
a += 3
print(id(a))

1891285100912
1891285101008


In [50]:
# a = [1,2]
# print(id(a))
# print(a)
# a += 1
# print(id(a))
# print(a)

1891393997824
[1, 2]


TypeError: 'int' object is not iterable

## axis가 같은 두 ndarray의 연산


## Broadcasting
- shape이 다른 두 개의 ndarray들을 이용해서 산술 연산을 할 때 numpy가 ndarrays를 처리하는 방법

## Shape이 같은 두 ndarray의 산술 연산
- 원소끼리 연산이 이루어짐.

In [21]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a + b


array([11, 22, 33])

In [22]:
a*b

array([10, 40, 90])

In [23]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
b = np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [25]:
a+b

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [26]:
a = np.array([1,2,3])
b = np.array([1,2])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [29]:
x = np.arange(1,5)
print(x)
print(x + 3)

[1 2 3 4]
[4 5 6 7]


In [30]:
print(x * 3)

[ 3  6  9 12]


In [31]:
print(x/3)

[0.33333333 0.66666667 1.         1.33333333]


In [32]:
x = np.arange(1,7).reshape(2,3)
print(x+3)

[[4 5 6]
 [7 8 9]]


In [33]:
print(3*x)

[[ 3  6  9]
 [12 15 18]]


In [34]:
a = np.arange(1,7).reshape(2,3)
b = np.array([[1, 2, 1]])
print(a + b)

[[2 4 4]
 [5 7 7]]


In [36]:
a = np.arange(1,7).reshape(2,3)
b = np.array([1, 2])
print(a + b)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [37]:
a = np.arange(1,7).reshape(2,3)
b = np.array([[1], [2]])
print(a + b)

[[2 3 4]
 [6 7 8]]


In [38]:
a = np.arange(1,7).reshape(2,3)
b = np.array([[1, 1], [2, 2]])
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [39]:
a = np.arange(1,9).reshape(2,4)
b = np.array([[1, 1], [2, 2]])
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [40]:
a = np.arange(1,25).reshape(2,3,4)
b = np.array([1, 2, 1, 2])
print(a + b)

[[[ 2  4  4  6]
  [ 6  8  8 10]
  [10 12 12 14]]

 [[14 16 16 18]
  [18 20 20 22]
  [22 24 24 26]]]


In [41]:
a = np.arange(1, 25).reshape(2,3,4)
b = np.arange(8).reshape(2,1,4)

In [42]:
print(a)
print(b)
print(a + b)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[0 1 2 3]]

 [[4 5 6 7]]]
[[[ 1  3  5  7]
  [ 5  7  9 11]
  [ 9 11 13 15]]

 [[17 19 21 23]
  [21 23 25 27]
  [25 27 29 31]]]


In [44]:
a = np.array([1,2,3]).reshape(3,1)
b = np.array([1,2,1]).reshape(1,3)
print(a, end=  "\n\n")
print(b, end=  "\n\n")
print(a + b)

[[1]
 [2]
 [3]]

[[1 2 1]]

[[2 3 2]
 [3 4 3]
 [4 5 4]]
